# Generated by Django 5.1.4 on 2025-01-10 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_enrollment_enrolled_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='course_type',
            field=models.CharField(blank=True, choices=[('student', 'For Students'), ('teacher', 'For Teachers')], default=None, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='sub_type',
            field=models.CharField(blank=True, choices=[('grade1', 'For 1st Grade'), ('grade2', 'For 2nd Grade')], default=None, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='topic',
            name='duration_in_minutes',
            field=models.PositiveIntegerField(blank=True, help_text='Продолжительность видео (в минутах)', null=True),
        ),
    ]
