# Generated by Django 5.1.4 on 2025-01-11 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_course_course_type_course_sub_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='img',
            field=models.ImageField(blank=True, help_text='Обложка курса или иконка', null=True, upload_to='courses/images/'),
        ),
    ]
