# Generated by Django 5.1.4 on 2025-01-14 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_course_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Есім')),
                ('phone', models.CharField(max_length=11, verbose_name='Телефон номері')),
                ('selected_pair', models.CharField(max_length=255, verbose_name='Пәндер жұбы')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Тіркелу күні')),
            ],
        ),
    ]
