# Generated by Django 5.1.5 on 2025-01-18 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_registration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('curator', 'Curator'), ('student', 'Student'), ('seller', 'Seller')], max_length=20),
        ),
    ]
